namespace ProtoRegister.Protos {
    public enum EItemDescType {
        GatheredFrom,
        MadeIn,
        FuelType,
        Energy,
        EnergyType,
        Power,
        EnergyEfficiency,
        FluidConsumption,
        InputPower,
        OutputPower,
        Accumulated,
        WorkConsumption,
        IdleConsumption,
        ConnectionLength,
        SupplyArea,
        TransportSpeed,
        NumberOfPorts,
        StorageSize,
        GatheringTarget,
        GatheringSpeed, //Mining
        SortingSpeed,
        CargoStacking,
        ProductionSpeed,
        HP,
        Storage,
        DroneCarryingCapacity,
        ShipCarryingCapacity2,
        FlightSpeed,
        ProduceAcceleration,
        TimesOfSpray,
        FluidCapacity,
        FuelChamberGen,
        GatheringSpeed2, //Acquisition
        ResearchSpeed,
        EjectSpeed,
        LaunchSpeed,
        Life,
        EnergyPotential,
        MaxChargingPower,
        BasicGeneration
    }
}